module.exports = {
  roleApplications: [],
  refereeInvitations: [],
  refereeSalaryConfigs: [],
  notificationCampaigns: [],
  notifications: [],
  depositOrders: [],
  withdrawals: [],
  paymentCallbacks: [],
  wallets: {},
  financeSettings: {
    platformFeePercent: 5,
    bettingTaxPercent: 0,
    withdrawalFee: 0,
  },
  racePrizeShares: [],
  provinces: [],
  venues: [],
  systemSettings: {
    fees: {},
    rules: {},
    emailTemplates: {},
    security: {},
    branding: {
      appName: "Horse Racing",
      logoUrl: "",
      primaryColor: "#0f766e",
    },
    raceDistances: [1000, 1200, 1600, 2000],
  },
  betMarkets: [],
  bets: [],
  auditLogs: [],
  adminWalletWithdrawals: [],
  complaints: [],
};
